<a href="https://colab.research.google.com/github/sulimanbadour1/donrs/blob/master/donrs%22hw2%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import sympy as sym  
from math import cos, radians, sin
from numpy import matrix

In [ ]:
def rotate(axis, theta, angular_units='radians'):
    '''Compute Basic Homogeneous Transform Matrix for
    rotation of "theta" about specified axis.'''
    #Verify string arguments are lowercase
    axis=axis.lower()
    angular_units=angular_units.lower()
    #Convert to radians if necessary
    if angular_units=='degrees':
        theta=radians(theta)
    elif angular_units=='radians':
        pass
    else:
        raise Exception('Unknown angular units.  Please use radians or degrees.')
    #Select appropriate basic homogenous matrix
    if axis=='x':
        rotation_matrix=matrix([[1, 0, 0, 0],
                               [0, cos(theta), -sin(theta), 0],
                               [0, sin(theta), cos(theta), 0],
                               [0, 0, 0, 1]])
    elif axis=='y':
        rotation_matrix=matrix([[cos(theta), 0, sin(theta), 0],
                               [0, 1, 0, 0],
                               [-sin(theta), 0, cos(theta), 0],
                               [0, 0, 0, 1]])  
    elif axis=='z':
        rotation_matrix=matrix([[cos(theta), -sin(theta), 0, 0],
                               [sin(theta), cos(theta), 0, 0],
                               [0, 0, 1, 0],
                               [0, 0, 0, 1]])
    else:
        raise Exception('Unknown axis of rotation.  Please use x, y, or z.')
    return rotation_matrix

In [ ]:
def translate(axis, d):
    '''Calculate Basic Homogeneous Transform Matrix for
    translation of "d" along specified axis.'''  
    #Verify axis is lowercase
    axis=axis.lower()
    #Select appropriate basic homogenous matrix
    if axis=='x':
        translation_matrix=matrix([[1, 0, 0, d],
                                  [0, 1, 0, 0],
                                  [0, 0, 1, 0],
                                  [0, 0, 0, 1]])
    elif axis=='y':
        translation_matrix=matrix([[1, 0, 0, 0],
                                  [0, 1, 0, d],
                                  [0, 0, 1, 0],
                                  [0, 0, 0, 1]])
    elif axis=='z':
        translation_matrix=matrix([[1, 0, 0, 0],
                                  [0, 1, 0, 0],
                                  [0, 0, 1, d],
                                  [0, 0, 0, 1]])
    else:
        raise Exception('Unknown axis of translation.  Please use x, y, or z.')
    return translation_matrix

In [ ]:
q1 = sym.Symbol('q1')
q2 = sym.Symbol('q2')
q3 = sym.Symbol('q3')
q4 = sym.Symbol('q4')
q5 = sym.Symbol('q5')
q6 = sym.Symbol('q6')

In [ ]:
#Calculate arbitrary homogeneous transformation matrix for CF0 to CF3
H0_1=rotate('z', 0, 'degrees')*translate('z', 1)
H1_2=translate('x', 1)*rotate('y', 0, 'degrees')*translate('z' ,1 )
H2_3=rotate('y', 0, 'degrees')*translate('z', 1)
H3_4=rotate('x',0,'degrees')*translate('x',1)*rotate('y',0,'degrees')*rotate('x',90,'degrees')
H4_5=translate('x',1)
H0_3=H0_1*H1_2*H2_3*H3_4*H4_5
print(H0_3)

[[ 1.000000e+00  0.000000e+00  0.000000e+00  3.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17  3.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


In [ ]:
#Calculate arbitrary homogeneous transformation matrix for CF0 to CF3
H0_1=rotate('z', 0, 'degrees')*translate('z', 0)
H1_2=translate('x', 0)*rotate('y', 0, 'degrees')*translate('z' ,0 )
H2_3=rotate('y', 0, 'degrees')*translate('z', 0)
H3_4=rotate('Z',0,'degrees')*translate('x',0)*rotate('y',-180,'degrees')*rotate('x',-90,'degrees')
H4_5=translate('x',0)
H0_3=H0_1*H1_2*H2_3*H3_4*H4_5
print(H0_3)

[[-1.00000000e+00  1.22464680e-16 -7.49879891e-33  0.00000000e+00]
 [ 0.00000000e+00  6.12323400e-17  1.00000000e+00  0.00000000e+00]
 [ 1.22464680e-16  1.00000000e+00 -6.12323400e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [ ]:
#Calculate arbitrary homogeneous transformation matrix for CF0 to CF3
H0_1=rotate('x', -90, 'degrees')
H1_2=rotate('z', 90, 'degrees')
#H2_3=rotate('y', 0, 'degrees')*translate('z', 0)
H0_3=H0_1*H1_2
print(H0_1)
print(H0_3)

[[ 1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17  1.000000e+00  0.000000e+00]
 [ 0.000000e+00 -1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[ 6.12323400e-17 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.12323400e-17  3.74939946e-33  1.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -6.12323400e-17  6.12323400e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [ ]:
#Calculate arbitrary homogeneous transformation matrix for CF0 to CF3
H0_1=rotate('Z', -90, 'degrees')*translate('z', 0)
H1_2=rotate('Y', -90, 'degrees')*translate('X', 0)
#H2_3=rotate('y', 0, 'degrees')*translate('z', 0)
H0_2=H1_2*H0_1
print(H0_2)

[[ 6.12323400e-17 -6.12323400e-17 -1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  3.74939946e-33  6.12323400e-17  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  6.12323400e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [ ]:
q1 = sym.Symbol('q1')
q2 = sym.Symbol('q2')
q3 = sym.Symbol('q3')
q4 = sym.Symbol('q4')
q5 = sym.Symbol('q5')
q6 = sym.Symbol('q6')

cos = sym.Symbol('cos')
sin = sym.Symbol('sin')

x = sym.Symbol('x')
y = sym.Symbol('y')
z = sym.Symbol('z')

In [ ]:
rot_z = [[cos*q1,-sin*q1,0,0],[sin*q1,cos*q1,0,0],[0,0,1,0],[0,0,0,1]]
rot_x = [[1,0,0,0], [0,cos*q1,-sin*q1,0,],[0, sin*q1,cos*q1,0,0],[0,0,0,1]]
rot_y =[[cos*q1,0,sin*q1,0,],[0,1,0,0],[-sin*q1,0,cos*q1,0,0],[0,0,0,1]]

In [ ]:
rot_y2 =[[cos*q2,0,sin*q2,0,],[0,1,0,0],[-sin*q2,0,cos*q2,0,0],[0,0,0,1]]

In [ ]:
rot_y3 =[[cos*q3,0,sin*q3,0,],[0,1,0,0],[-sin*q3,0,cos*q3,0,0],[0,0,0,1]]

In [ ]:
rot_x4 = [[1,0,0,0], [0,cos*q4,-sin*q4,0,],[0, sin*q4,cos*q4,0,0],[0,0,0,1]]

In [ ]:
rot_y5 =[[cos*q5,0,sin*q5,0,],[0,1,0,0],[-sin*q5,0,cos*q5,0,0],[0,0,0,1]]

In [ ]:
rot_x6 = [[1,0,0,0], [0,cos*q6,-sin*q6,0,],[0, sin*q6,cos*q6,0,0],[0,0,0,1]]

In [ ]:
tr_x = [[1,0,0,1],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
tr_y = [[1,0,0,0],[0,1,0,1],[0,0,1,0],[0,0,0,1]]
tr_z = [[1,0,0,0],[0,1,0,0],[0,0,1,1],[0,0,0,1]]

H=RZ(Q1)*TZ(D1)*TX(A1)RY(Q2)*TZ(A2)*RY(-Q3)*TZ(A3)*RX(-Q4)*TX(D4)*RY(-Q5)*RX(-Q6)*TX(D6)


In [ ]:
H=rot_z*tr_z*tr_x*rot_y2*tr_z*rot_y3*tr_z*rot_x4*tr_x*rot_y5*rot_x6 # not 

TypeError: ignored

#HERE IS THE LAST MATRIX "FK".



[ cos(q5)*(cos(q1)*cos(q2)*cos(q3) + cos(q1)*sin(q2)*sin(q3)) - sin(q5)*(sin(q1)*sin(q4) + cos(q4)*(cos(q1)*cos(q2)*sin(q3) - cos(q1)*cos(q3)*sin(q2))), sin(q6)*(cos(q5)*(sin(q1)*sin(q4) + cos(q4)*(cos(q1)*cos(q2)*sin(q3) - cos(q1)*cos(q3)*sin(q2))) + sin(q5)*(cos(q1)*cos(q2)*cos(q3) + cos(q1)*sin(q2)*sin(q3))) - cos(q6)*(cos(q4)*sin(q1) - sin(q4)*(cos(q1)*cos(q2)*sin(q3) - cos(q1)*cos(q3)*sin(q2))), - sin(q6)*(cos(q4)*sin(q1) - sin(q4)*(cos(q1)*cos(q2)*sin(q3) - cos(q1)*cos(q3)*sin(q2))) - cos(q6)*(cos(q5)*(sin(q1)*sin(q4) + cos(q4)*(cos(q1)*cos(q2)*sin(q3) - cos(q1)*cos(q3)*sin(q2))) + sin(q5)*(cos(q1)*cos(q2)*cos(q3) + cos(q1)*sin(q2)*sin(q3))), cos(q1)*(a1 + a2*sin(q2) + d4*cos(q2 - q3) + a3*sin(q2 - q3))]
[ sin(q5)*(cos(q1)*sin(q4) - cos(q4)*(cos(q2)*sin(q1)*sin(q3) - cos(q3)*sin(q1)*sin(q2))) + cos(q5)*(sin(q1)*sin(q2)*sin(q3) + cos(q2)*cos(q3)*sin(q1)), cos(q6)*(cos(q1)*cos(q4) + sin(q4)*(cos(q2)*sin(q1)*sin(q3) - cos(q3)*sin(q1)*sin(q2))) - sin(q6)*(cos(q5)*(cos(q1)*sin(q4) - cos(q4)*(cos(q2)*sin(q1)*sin(q3) - cos(q3)*sin(q1)*sin(q2))) - sin(q5)*(sin(q1)*sin(q2)*sin(q3) + cos(q2)*cos(q3)*sin(q1))),   sin(q6)*(cos(q1)*cos(q4) + sin(q4)*(cos(q2)*sin(q1)*sin(q3) - cos(q3)*sin(q1)*sin(q2))) + cos(q6)*(cos(q5)*(cos(q1)*sin(q4) - cos(q4)*(cos(q2)*sin(q1)*sin(q3) - cos(q3)*sin(q1)*sin(q2))) - sin(q5)*(sin(q1)*sin(q2)*sin(q3) + cos(q2)*cos(q3)*sin(q1))), sin(q1)*(a1 + a2*sin(q2) + d4*cos(q2 - q3) + a3*sin(q2 - q3))]
[                                                                                                   cos(q2 - q3)*cos(q4)*sin(q5) - sin(q2 - q3)*cos(q5),                                                                                                                                                            - sin(q6)*(sin(q2 - q3)*sin(q5) + cos(q2 - q3)*cos(q4)*cos(q5)) - cos(q2 - q3)*cos(q6)*sin(q4),                                                                                                                                                                cos(q6)*(sin(q2 - q3)*sin(q5) + cos(q2 - q3)*cos(q4)*cos(q5)) - cos(q2 - q3)*sin(q4)*sin(q6),           d1 + a2*cos(q2) + a3*cos(q2 - q3) - d4*sin(q2 - q3)]
[                                                                                                                                                     0,                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                           0,                                                             1]
